# Welcome to Jekyll!
#

# Site settings
title: Pei Jie 
# description: 
owner: Pei Jie Sim # or company name
email: peijiesim@berkeley.edu
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://peijie.me" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/simpeijie
  github: https://github.com/simpeijie
  email: peijiesim@berkeley.edu
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed

